# Generated by Django 2.0 on 2018-07-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
