# Generated by Django 2.0 on 2018-07-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_choice_is_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='Date'),
        ),
    ]
